#! /bin/bash

# Create icons
flutter pub run flutter_launcher_icons:main

# Build web app
flutter build web

# Build linux app
flutter build linux
# -->
tar czf build/linux/x64/release/Flounder.tar.gz --directory=build/linux/x64/release/bundle/ .
cp build/linux/x64/release/Flounder.tar.gz packages/Flounder.tar.gz

# Build android app
flutter build apk
# -->
cp build/app/outputs/flutter-apk/app-release.apk packages/Flounder.apk

# Build windows app
#flutter build windows
#flutter pub run msix:create
